# Generated by Django 3.1.2 on 2020-10-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgery_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Please_Select_Image_to_Detect_Forgery',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
    ]
