# Generated by Django 3.1.2 on 2020-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgery_detection', '0002_auto_20201029_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Please_Select_Image_to_Detect_Forgery',
            field=models.ImageField(upload_to='input_images/'),
        ),
    ]
