# Generated by Django 3.1.2 on 2020-10-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgery_detection', '0003_auto_20201029_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Input_Folder',
        ),
    ]
