# Generated by Django 3.1.2 on 2020-10-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgery_detection', '0004_auto_20201029_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input_Folder',
            new_name='database',
        ),
    ]
